// *********************************************************************
// Copyright 2018 Healthy Bytes Technology & Wellness
//
// An uglify-es plugin for Brunch.

'use strict';

const debug = require('debug')('brunch:uglify-es');

// Use the real TSLint library, or our mock library if we're testing.
let uglify;
if (! process.env.hasOwnProperty('TEST'))
{
  uglify = require('uglify-es');
}
else
{
  debug('Using mock uglify-es library');
  uglify = require('./test/MockUglify');
}

class Uglifier
{
  // -------------------------------------------------------------------------
  // Construct the plugin with the entire Brunch config object.  We will pick
  // out our options from the plugins.uglify-es object.  See README.md for
  // documentation of the options.
  //
  // GOTCHA: We reference the given options - we don't make a copy.  This
  // means that uglify-es may modify the given options, for example the
  // nameCache option.
  //
  // If the warnings option is defined and non-false, then all warnings
  // generated by uglify-es will be treated as errors.
  //
  constructor(brunchCfg)
  {
    // Find out plugin's options within the global Brunch plugin
    // configuration, or use an empty config.
    //
    // The config supplied by Brunch is expected to be whatever options are
    // accepted by uglify-es as described in the API References section here:
    //
    // https://www.npmjs.com/package/uglify-es
    //
    // We don't parse or normalize anything supplied here.  It gets passed to
    // each file we're asked to optimize.
    //
    this.cfg = (brunchCfg
                && brunchCfg.plugins
                && brunchCfg.plugins['uglify-es']
		? brunchCfg.plugins['uglify-es']
		: {});
  }

  // -------------------------------------------------------------------------
  // Optimize a single file using the config supplied during construction.
  // This returns a resolved Promise of the optimized data, or a rejected
  // Promise with the error that occurred.
  //
  optimize(brunchFile)
  {
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // If Brunch gave us source map info, then we must ask uglify-es to modify
    // it to match the optimized output.

    if (brunchFile.map)
    {
      this.cfg.sourceMap =
        {
          filename: brunchFile.path,
          // Brunch passes in a source-map SourceMapGenerator object, and
          // uglify-es wants the equivalent JSON.
          content: brunchFile.map.toJSON()
          // We omit the 'url' field here to inhibit uglify-es from appending
          // the '//# sourceMappingUrl=foo' line to the end of the optimized
          // code.  Brunch will add its own URL line, so we don't need the one
          // that uglify-es would otherwise generate.
        };
    }
    
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // Perform the optimization.  This may modify the cfg.

    const optimized = uglify.minify(brunchFile.data, this.cfg);

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // Check for any errors.

    let error = undefined;

    // Were separate warnings specified?
    if (! this.cfg.hasOwnProperty('warnings')
        || (typeof this.cfg.warnings === 'boolean'
            && this.cfg.warnings === false))
    {
      // No, so just look for errors.
      if (optimized.error !== undefined)
      {
        error = optimized.error;
      }
    }
    // Warnings and errors are separate, so combine them.
    else
    {
      let errorStr = '';
      
      if (optimized.error !== undefined)
      {
        errorStr = `Errors: ${optimized.error}`;
      }

      if (optimized.warnings !== undefined)
      {
        if (errorStr.length !== 0)
        {
          errorStr += '\n';
        }
        errorStr += `Warnings: ${optimized.warnings}`;
      }

      error = new Error(errorStr);
    }

    // Did we find any errors/warnings?
    if (error !== undefined)
    {
      // Reject with the error.
      return Promise.reject(error);
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // Build the result to return to Brunch.

    let result = { data: optimized.code };

    // Add the new source map, if one was passed in.
    if (brunchFile.map)
    {
      // Clear the original source map config so it doesn't pollute the next
      // call to optimize().
      delete this.cfg.sourceMap;

      // Brunch expects the optimized source map as a string, which is how
      // uglify-es returns it.
      result.map = optimized.map;
    }
    
    // Return the result.
    return Promise.resolve(result);
  }
}

// Tell Brunch that we are a plugin, and we handle code source files.
//
// Note that the presence of an optimize() function on Uglifier tells Brunch
// that we're an optimizer.
//
Uglifier.prototype.brunchPlugin = true;
Uglifier.prototype.type = 'javascript';

module.exports = Uglifier;

// *********************************************************************
